version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 13306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: mmplugin_parser
      MYSQL_USER: "mmuser"
      MYSQL_PASSWORD: "mostest"
  metabase:
      image: metabase/metabase:v0.32.8 
      restart: always
      ports:
        - 3000:3000
      volumes:
        - ./metabase-data:/metabase-data
      depends_on:
        - db
      environment:
        MB_DB_DBNAME: "mmplugin_parser"
        MB_DB_HOST: db
        MB_DB_PORT: 3306
        MB_DB_USER: "mmuser"
        MB_DB_PASS: "mostest"
        MB_DB_FILE: /metabase-data/metabase.db
