version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 13306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: mmplugin_parser
      MYSQL_USER: "mmuser"
      MYSQL_PASSWORD: "mostest"
