name: Run

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
          - 3306
    env:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mmplugin_parser
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # - name: Cache go modules
      #   if: runner.os != 'Windows'
      #   uses: actions/cache@preview
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-
      # - name: Setup depencencies of go
      #   run: go mod tidy
      #   working-directory: ./server
      # - name: Cache node modules
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-
      # - name: Setup dependencies of npm
      #   run: npm install
      #   working-directory: ./webapp
      - name: debug
        run: echo $PORT
        env:
          PORT: ${{ job.services.mysql.ports['3306']}}
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
      - name: debug
        run: export
      - name: Setup mysql
        run: ls initdb/*.sql | sort | xargs cat | mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} --host ${MYSQL_HOST} -P ${PORT} 
        env:
          PORT: ${{ job.services.mysql.ports['3306']}}
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
      - name: Run
        run: ./run.sh
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
      - name: report
        run: node report.js
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
